export const pairInfo = {
    "00" : { pros: "-", cons: "-" },
    "01" : { pros: "-", cons: "-" },
    "02" : { pros: "-", cons: "-" },
    "03" : { pros: "-", cons: "-" },
    "04" : { pros: "-", cons: "-" },
    "05" : { pros: "-", cons: "-" },
    "06" : { pros: "-", cons: "-" },
    "07" : { pros: "-", cons: "-" },
    "08" : { pros: "-", cons: "-" },
    "09" : { pros: "-", cons: "-" },
    "10" : { pros: "-", cons: "-" },
    "11" : { pros: "Leadership, Authority, Intuition, Spiritual", cons: "None", nature: "positive" },
    "12" : { pros: "Attractive face, saving person, Helpful life partner", cons: "None", nature: "positive" },
    "13" : { pros: "Well Educated, Reputed Work, Good Health, Good Marriage Life, Respected, Popular, Special in Circle / Network, Civil Services", cons: "None", nature: "positive" },
    "14" : { pros: "None", cons: "Person can get attracted to Loan liabilities, Legal Notice, Health issues, Hard work, Toughness Number", nature: "negative" },
    "15": { pros: "Successful in Exams, Comfort or Luxury, Support by father, Supportive for marriage, Father’s popularity, make their father famous (good cause)", cons: "None", nature: "positive" },
    "16" : { pros: "None", cons: "(Most Negative) Spouse health issues, married life issues, income confined", nature: "negative" },
    "17": { pros: "Government Connections, Leadership, Good Contacts, Networker", cons: "None", nature: "positive" },
    "18" : { pros: "None", cons: "(Very Negative) Spouse health issue, understanding issues in father & son, Govt. related issue, change in job frequently", nature: "negative" },
    "19": { pros: "Freedom Lover, Highly Educated, Independent Worker, Occupy High Posts, Occupy Highest Posts", cons: "None", nature: "positive" },
    "20" : { pros: "-", cons: "-" },
    "21" : { pros: "Attractive face, Helpful life partner ", cons: "Waste of Money", nature: "positive" },
    "22" : { pros: "Mastery, Building, Achieving great things", cons: "None", nature: "positive" },
    "23" : { pros: "Win over enemies, Fun Loving, Generally many enemy but none of them will be able to harm he native", cons: "Extra marital affair, May not be happy from children", nature: "positive" },
    "24" : { pros: "Keep patience to achieve something, Makes different plans and brain actively processing those plans", cons: "Negative/destructive thinking", nature: "negative" },
    "25" : { pros: "Interested in Occult Science, Blessed Magical Powers, Self Healing, Good Motivator, Air Travelling", cons: "None", nature: "positive" },
    "26" : { pros: "None", cons: "Barrier in Studies or Break in education , Girl- Problem with mother in law, Attraction towards money or opposite sex, Chances of less Sperm count or Diabetes", nature: "negative" },
    "27" : { pros: "Good intuition", cons: "Joint pain Or Urine related disease, Arthritis (Vaat Issue)", nature: "negative" },
    "28" : { pros: "Person have decent amount of Money", cons: "Vish-Yog, Excessive Medical/Hospital Expenditure, 2 marriages in the Family, Avoid Bad company (Harm you)", nature: "negative" },
    "29" : { pros: "Person have decent amount of Money, Live happily on the money of Someone else, Native might become Egoistic", cons: "None", nature: "positive" },
    "30" : { pros: "-", cons: "-" },
    "31": { pros: "Well Educated, Reputed Work, Good Health, Good Marriage Life, Respected, Popular, Special in Circle / Network, Civil Services", cons: "None", nature: "positive" },
    "32" : { pros: "Win over enemies, Fun Loving, Generally many enemy but none of them will be able to harm he native", cons: "Extra marital affair, May not be happy from children", nature: "positive" },
    "33" : { pros: "Knowledgeable", cons: "None", nature: "positive" },
    "34" : { pros: "None", cons: "Child & Parent Separated, Breathing Issue, Heart Diseases, Legs Shivering, Paralysis, Someone in Family Paralytic, Less Confidence, Stubborn", nature: "negative" },
    "35" : { pros: "Get success away from home, Successful, Good economical conditions", cons: "Fear of father, Less liquid cash", nature: "positive" },
    "36" : { pros: "Multi-talented, Religious, Attitude & Self Respect is priority, Knowledgeable, Follows Strict Rules & Regulations in Life", cons: "Delay in Marriage, More of Principal oriented person, Barrier in Studies, struggle in presentation", nature: "positive" },
    "37" : { pros: "Top Position in Respective Field, Financial Support, Strong Intentions for Work", cons: "None", nature: "positive" },
    "38" : { pros: "Property Field Beneficial, Sales Field Beneficial, Real Estate, Counselor, Mediator, Broker", cons: "None", nature: "positive" },
    "39" : { pros: "Active, Intelligent, Hard Worker, Social Worker", cons: "None", nature: "positive" },  
    "40" : { pros: "-", cons: "-" },
    "41" : { pros: "None", cons: "Person can get attracted to Loan liabilities, Legal Notice, Health issues, Hard work, Toughness Number", nature: "negative" },
    "42" : { pros: "Keep patience to achieve something, Makes different plans and brain actively processing those plans", cons: "Negative/destructive thinking", nature: "negative" },
    "43" : { pros: "None", cons: "Child & Parent Separated, Breathing Issue, Heart Diseases, Legs Shivering, Paralysis, Someone in Family Paralytic, Less Confidence, Stubborn", nature: "negative" },
    "44" : { pros: "Hardworking", cons: "None", nature: "negative" },
    "45" : { pros: "None", cons: "Needs to visit Hospital visits for different medical reasons and Court for different issues, Life with Restrictions", nature: "negative" },
    "46" : { pros: "None", cons: "Skin Disease, Patches in the Skin, Piles, Extra Relationship, UTI Infection, Inter Cast Marriage, Avoid this Pair for Kids", nature: "negative" },
    "47" : { pros: "Clever Personality, Service Provider, Strong Determination, Strong Will Power, Self Problem Solver, Honest, Brilliant, Jugadoo", cons: "None", nature: "positive" },
    "48" : { pros: "None", cons: "(Very Negative) Blood related disease, Incurable problems, Deficiency in sexual pleasure", nature: "negative" },
    "49" : { pros: "None", cons: "Do risky work , Uniform work, Criminal minded", nature: "negative" },
    "50" : { pros: "-", cons: "-" },
    "51" : { pros: "Successful in Exams, Comfort or Luxury, Support by father, Supportive for marriage, Father’s popularity, make their father famous (good cause)", cons: "None", nature: "positive" },
    "52" : { pros: "Interested in Occult Science, Blessed Magical Powers, Self Healing, Good Motivator, Air Travelling", cons: "None", nature: "positive" },
    "53" : { pros: "Get success away from home, Successful, Good economical conditions", cons: "Fear of father, Less liquid cash", nature: "positive" },
    "54" : { pros: "None", cons: "Needs to visit Hospital visits for different medical reasons and Court for different issues, Life with Restrictions", nature: "negative" },
    "55" : { pros: "Communication, Money Flow", cons: "None", nature: "positive" },
    "56" : { pros: "None", cons: "Money Stuck, Hesitate to ask own money, Failure in Love, Less Expressive, Business minded", nature: "negative" },
    "57" : { pros: "Good Public Speaker, Good Businessman, Writer, Astrologer, Public Relations", cons: "None", nature: "positive" },
    "58" : { pros: "None", cons: "Money stuck, Talks about Lacs & Crores, Complete Financial Loss, Property Money Block, Calculated Minded", nature: "negative" },
    "59" : { pros: "Sharp Minded, Straight Forward, Immense Technical Knowledge, Successful Businessman, Rude, Few but Good Relations", cons: "None", nature: "positive" },
    "60" : { pros: "-", cons: "-" },
    "61" : { pros: "None", cons: "(Most Negative) Spouse health issues, married life issues, income confined", nature: "negative" },
    "62" : { pros: "None", cons: "Barrier in Studies or Break in education , Girl- Problem with mother in law, Attraction towards money or opposite sex, Chances of less Sperm count or Diabetes", nature: "negative" },
    "63" : { pros: "Multi-talented, Religious, Attitude & Self Respect is priority, Knowledgeable, Follows Strict Rules & Regulations in Life", cons: "Delay in Marriage, More of Principal oriented person, Barrier in Studies, struggle in presentation", nature: "positive" },
    "64" : { pros: "None", cons: "Skin Disease, Patches in the Skin, Piles, Extra Relationship, UTI Infection, Inter Cast Marriage, Avoid this Pair for Kids", nature: "negative" },
    "65" : { pros: "None", cons: "Money Stuck, Hesitate to ask own money, Failure in Love, Less Expressive, Business minded", nature: "negative" },
    "66" : { pros: "Luxury, Love, Responsibility", cons: "None", nature: "positive" },
    "67" : { pros: "Chance of Love marriage", cons: "Spouse health issues, Chances of disturbed married life, Chances of extra martial affairs", nature: "negative" },
    "68" : { pros: "Hospital / Health Services, Surgeon / Doctors", cons: "Health Problem, Eye, Chest / Breast Problems", nature: "negative" },
    "69" : { pros: "Family Oriented, Creative mind, Good Management Skills, Good Planner", cons: "None", nature: "positive" },
    "70" : { pros: "-", cons: "-" },
    "71" : { pros: "Government Connections, Leadership, Good Contacts, Networker", cons: "None", nature: "positive" },
    "72" : { pros: "Good intuition", cons: "Joint pain Or Urine related disease, Arthritis (Vaat Issue)", nature: "negative" },
    "73" : { pros: "Top Position in Respective Field, Financial Support, Strong Intentions for Work", cons: "None", nature: "positive" },
    "74" : { pros: "Clever Personality, Service Provider, Strong Determination, Strong Will Power, Self Problem Solver, Honest, Brilliant, Jugadoo", cons: "None", nature: "positive" },
    "75" : { pros: "Good Public Speaker, Good Businessman, Writer, Astrologer, Public Relations", cons: "None", nature: "positive" },
    "76" : { pros: "Chance of Love marriage", cons: "Spouse health issues, Chances of disturbed married life, Chances of extra martial affairs", nature: "negative" },
    "77" : { pros: "Researcher, Overthinking", cons: "None", nature: "negative" },
    "78" : { pros: "Spiritual Healer, Social Worker, Problem Solver, Self Problem Solver", cons: "Negative Thoughts, Loneliness", nature: "positive" },
    "79" : { pros: "None", cons: "Up down in Career, Rollercoaster Career, Joint Pains, Kidney Problems, Domestic Life disturbance", nature: "negative" },
    "80" : { pros: "-", cons: "-" },
    "81" : { pros: "None", cons: "(Very Negative) Spouse health issue, understanding issues in father & son, Govt. related issue, change in job frequently", nature: "negative" },
    "82" : { pros: "Person have decent amount of Money", cons: "Vish-Yog, Excessive Medical/Hospital Expenditure, 2 marriages in the Family, Avoid Bad company (Harm you)", nature: "negative" },
    "83" : { pros: "Property Field Beneficial, Sales Field Beneficial, Real Estate, Counselor, Mediator, Broker", cons: "None", nature: "positive" },
    "84" : { pros: "None", cons: "(Very Negative) Blood related disease, Incurable problems, Deficiency in sexual pleasure", nature: "negative" },
    "85" : { pros: "None", cons: "Money stuck, Talks about Lacs & Crores, Complete Financial Loss, Property Money Block, Calculated Minded", nature: "negative" },
    "86" : { pros: "Hospital / Health Services, Surgeon / Doctors", cons: "Health Problem, Eye, Chest / Breast Problems", nature: "negative" },
    "87" : { pros: "Spiritual Healer, Social Worker, Problem Solver, Self Problem Solver", cons: "Negative Thoughts, Loneliness", nature: "positive" },
    "88" : { pros: "None", cons: "Hardness, Judgmental", nature: "negative" },
    "89" : { pros: "Work with Principle, Astrologers, Consultants, Service Providers, Advocates, Stock Broker", cons: "Aggressive, Logical Arguments, Argument with Brother", nature: "negative" },
    "90" : { pros: "-", cons: "-" },
    "91" : { pros: "Freedom Lover, Highly Educated, Independent Worker, Occupy High Posts, Occupy Highest Posts", cons: "None", nature: "positive" },
    "92" : { pros: "Person have decent amount of Money, Live happily on the money of Someone else, Native might become Egoistic", cons: "None", nature: "positive" },
    "93" : { pros: "Active, Intelligent, Hard Worker, Social Worker", cons: "None", nature: "positive" },
    "94" : { pros: "None", cons: "Do risky work , Uniform work, Criminal minded", nature: "negative" },
    "95" : { pros: "Sharp Minded, Straight Forward, Immense Technical Knowledge, Successful Businessman, Rude, Few but Good Relations", cons: "None", nature: "positive" },
    "96" : { pros: "Family Oriented, Creative mind, Good Management Skills, Good Planner", cons: "None", nature: "positive" },
    "97" : { pros: "None", cons: "Up down in Career, Rollercoaster Career, Joint Pains, Kidney Problems, Domestic Life disturbance", nature: "negative" },
    "98" : { pros: "Work with Principle, Astrologers, Consultants, Service Providers, Advocates, Stock Broker", cons: "Aggressive, Logical Arguments, Argument with Brother", nature: "negative" },
    "99" : { pros: "Energetic, Active", cons: "None", nature: "positive" },
    "222" : { pros: "None", cons: "Mood swings, Depression, Too much emotional, BP Problem" },
    "444" : { pros: "None", cons: "Delay, Struggle, Obstacles, Less grounded " },
    "666" : { pros: "None", cons: "More travelling with no use, At the time not allowed to use at need" },
    "777" : { pros: "None", cons: "Mood swings, Internal disturbances, Overthinking & Anxiety, Diabetes, Joint problems" },
    "888" : { pros: "None", cons: "Delay, Struggle, Disturbances, Slow progress , Up-down in life" },
    "999" : { pros: "None", cons: "Debt, Anger issues, Blood related issues, Chances of skin patches" },
  };

